### ISSUE TITLE
Bug in uploading image

### ISSUE THREAD

**Issue by rrr3da** [DeuxHuitHuit/craft-cloudflare-images#6]
Hi,

I'm trying the plugin on a local DDEV environment.

I've set up the plugin with the ID, HASH and API TOKEN provided by Cloudflare, and activated the Flexible Variants as well.

I've created a Volume related to Cloudflare in the Craft dashboard, but every time I try to upload an image, let's say "WM_investment_image.jpg", I get an error.

Here is the log I found in the storage:

```php
2024-09-02 16:55:31 [web.ERROR] [Exception] Exception: Invalid filename: WM_investment_image.jpg in /var/www/html/vendor/deuxhuithuit/craft-cloudflare-images/src/Filename.php:13
Stack trace:
#0 /var/www/html/vendor/deuxhuithuit/craft-cloudflare-images/src/behaviors/CloudflareImagesAssetBehavior.php(20): deuxhuithuit\cfimages\Filename::toParts('WM_investment_i...')
#1 [internal function]: deuxhuithuit\cfimages\behaviors\CloudflareImagesAssetBehavior->cloudflareImagesUrl()
#2 /var/www/html/vendor/yiisoft/yii2/base/Component.php(305): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2372): yii\base\Component->__call('cloudflareImage...', Array)
#4 /var/www/html/vendor/deuxhuithuit/craft-cloudflare-images/src/imagetransforms/CloudflareImagesTransformer.php(81): craft\base\Element->__call('cloudflareImage...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/elements/Asset.php(2170): deuxhuithuit\cfimages\imagetransforms\CloudflareImagesTransformer->getTransformUrl(Object(craft\elements\Asset), Object(craft\models\ImageTransform), false)
#6 /var/www/html/vendor/craftcms/cms/src/elements/Asset.php(2097): craft\elements\Asset->_url(Object(craft\models\ImageTransform), false)
#7 /var/www/html/vendor/craftcms/cms/src/services/Assets.php(689): craft\elements\Asset->getUrl(Object(craft\models\ImageTransform))
#8 /var/www/html/vendor/craftcms/cms/src/elements/Asset.php(2217): craft\services\Assets->getThumbUrl(Object(craft\elements\Asset), 30, 25, false)
#9 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3848): craft\elements\Asset->thumbUrl(30)
#10 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(384): craft\base\Element->getThumbHtml(30)
#11 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(529): craft\helpers\Cp::chipHtml(Object(craft\elements\Asset), Array)
#12 /var/www/html/storage/runtime/compiled_templates/44/445ee65d03aedf3c861a5fade6748378.php(149): craft\helpers\Cp::elementChipHtml(Object(craft\elements\Asset), Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f6f41454f9c02d9baefc4511505c3f4c->doDisplay(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/ad/ad78d17fcede771eaf45e047745de0e2.php(154): Twig\Template->display(Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_21abf849488d12aace3fb29435696dd4->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#19 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#20 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render('_elements/table...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1293): craft\web\View->renderTemplate('_elements/table...', Array)
#23 /var/www/html/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(855): craft\base\Element::indexHtml(Object(craft\elements\db\AssetQuery), Array, Array, 'volume:b2d2b243...', 'index', true, true, false)
#24 /var/www/html/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(176): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#25 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#26 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-elements', Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('element-indexes...', Array)
#30 /var/www/html/vendor/craftcms/cms/src/web/Application.php(648): craft\web\Application->runAction('element-indexes...', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#32 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /var/www/html/web/index.php(12): yii\base\Application->run()
#34 {main} {"memory":2072280,"exception":"[object] (Exception(code: 0): Invalid filename: WM_investment_image.jpg at /var/www/html/vendor/deuxhuithuit/craft-cloudflare-images/src/Filename.php:13)"} 
```

toParts fails splitting the filename in 3 parts.. Am I missing something?

Bye

**Comment by rrr3da** [comment]
As soon as I try to upload the first image, then the asset listing fails in the dashboard.

![Screenshot 2024-09-02 alle 17 04 49](https://github.com/user-attachments/assets/8c74f0fc-7227-42b3-8420-14fb3e9125af)

The only way I have to fix this is manually remove rows from the DB...

**Comment by rrr3da** [comment]
FYI, the image is correctly uploaded to Cloudflare Images

**Comment by rrr3da** [comment]
System Report:

PHP version 8.2.22
Linux 6.10.0-linuxkit
MySQL 8.0.36
Imagick 3.7.0 (ImageMagick 6.9.11-60)
Craft Solo 5.3.6
Yii 2.0.51
Twig v3.8.0
Guzzle 7.9.2

Cloudflare Images 2.0.1

**Comment by rrr3da** [comment]
The issue is related to the asset-type field entry "Default Upload Location" setting. If you leave it blank, the plugin fails to operate.

Can you enforce the condition on that specific setting to be mandatory?

Feel free to close the issue, have a nice day

Stefano

**Comment by nitriques** [comment]
Hey @rrr3da 

Does it works if you rename the file ? I think that the 2 `_` are confusing our code...

**Comment by nitriques** [comment]
Also @rrr3da What are you referring to as "Default Upload Location" ?

I've check both the FS settings and plugin setting and I see nothing.

**Comment by rrr3da** [comment]
Hello @nitriques the undescores do not have an impact on the plugin behaviour.

I tried the plugin on an online dev- subdomain (so, no DDEV local environment) and everything seems to work as expected.

Anyway, our company decided to move to Digital Ocean Spaces... I don't have an active Cloudflare Images account anymore to do any further test.

Have a nice day

**Comment by nitriques** [comment]
Hey @rrr3da Thanks for the follow up.

When in a DDEV env, it should work just fine no ? The VM just need to be connected to the internet...

Thanks again. 

(Shameless plug: Check our Cloudflare Stream plugin if you need to deal with videos hehe)
